name: Minify and Commit

on:
  push:
    branches:
      - main  # Anda bisa mengganti dengan branch yang sesuai

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        # Instal cleancss menggunakan npm
        npm install -g clean-css-cli

    - name: Minify CSS files
      run: |
        # Membuat direktori dist jika belum ada
        mkdir -p dist

        # Menemukan semua file CSS di direktori src dan meminify ke dist
        find src -name "*.css" | while read file; do
          # Membuat direktori di dalam dist yang sesuai dengan struktur src
          mkdir -p dist/$(dirname "${file#src/}")
          # Meminify file CSS menggunakan cleancss (pastikan cleancss sudah terinstal)
          cleancss -o "dist/${file#src/}" "$file"
        done

    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Minify files and update dist"
        branch: ${{ github.ref }}  # Menargetkan branch yang sama dengan tempat workflow dijalankan
