name: Minify and Commit Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install terser html-minifier clean-css-cli

      # Prepare dist directory
      - name: Prepare dist directory
        run: rm -rf dist && mkdir -p dist

      # Minify JavaScript files
      - name: Minify JavaScript files
        run: |
          find src -name "*.js" | while read file; do
            mkdir -p dist/$(dirname "${file#src/}")
            terser "$file" -o "dist/${file#src/}"
          done

      # Minify HTML files
      - name: Minify HTML files
        run: |
          find src -name "*.html" | while read file; do
            mkdir -p dist/$(dirname "${file#src/}")
            html-minifier --collapse-whitespace --remove-comments --minify-js true --minify-css true -o "dist/${file#src/}" "$file"
          done

      # Minify CSS files
      - name: Minify CSS files
        run: |
          find src -name "*.css" | while read file; do
            mkdir -p dist/$(dirname "${file#src/}")
            cleancss -o "dist/${file#src/}" "$file"
          done

      # Commit and push changes
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dist
          git commit -m "Minify files and update dist" || echo "No changes to commit"
          git push origin main
